### ISSUE TITLE
unable to resolve module @env

### ISSUE THREAD

**Issue by barron9** [tusbar/babel-plugin-dotenv-import#113]
@env folder place in project folder but it gives error

**Comment by lrholmes** [comment]
Hey @barron9, I'm encountering this issue. Can you elaborate on the solution or why you closed this please?

**Comment by TrebuhD** [comment]
@lrholmes if you're using TypeScript, you can create a `@types/@env.d.ts` file like this:

```typescript
declare module "@env" {
  const API_URL: string;
  const API_KEY: string;
  // ...rest of your .env variables
}
```

One downside is you need to update this file every time if you add a new environment variable.
