### ISSUE TITLE
convert boolean values and numbers into native types

### ISSUE THREAD

**Issue by pke** [tusbar/babel-plugin-dotenv-import#142]
Wouldn't it be nice if the plugin would convert boolean string values to native boolean values and numbers to native numbers?

This could be enabled (for backward compat) and customised via config.

```json
"dotenv-import", {
  "types": true,
}
```

|input|output|
|-----|------|
|1|Number|
|1.2|Number|
|1.2ms|string|
|true|`true`|
|false|`false`|

Maybe, if that does not drives it too far, add mapper to the config

```json
"dotenv-import", {
  "types": {
    "boolean": "/yes|no|true|false/i"
  },
}
```

**Comment by tusbar** [comment]
Hello, thank you for the suggestion but it’s not in the scope of this library.

It exposes environment variables, and environment variables are strings.
