### ISSUE TITLE
Android release build picking up debug environment variables instead of prod

### ISSUE THREAD

**Issue by Sterlingryan** [tusbar/babel-plugin-dotenv-import#168]
I'm having an issue where the Android release build is picking up the variables inside .env instead of variables inside .env.production. iOS works fine.

"react-native": "0.62.2",
"react-native-dotenv": "^2.3.0",
"babel-plugin-dotenv-import": "^2.1.0",

.bablerc:
```
{
    "plugins": [
        "add-react-displayname",
        "./node_modules/@heap/react-native-heap/instrumentor/src/index.js",
        ["dotenv-import", {
            "moduleName": "@env",
            "path": ".env",
            "blacklist": null,
            "whitelist": null,
            "safe": false,
            "allowUndefined": true
        }],
    ]
}
```
babel.config.js
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};
```

**Comment by goatandsheep** [comment]
Set path to `.env.production`

**Comment by SirKadogan** [comment]
I'm having a similar issue. In my case development gets production and production gets development. 

On expo and running android

**Comment by goatandsheep** [comment]
@SirKadogan I'm working on adding multi env support to https://github.com/goatandsheep/react-native-dotenv/issues/1

But it's a fork from this package so @Sterlingryan I'd recommend against using both

**Comment by tusbar** [comment]
If you need multiple .env file support, use [different environments](https://babeljs.io/docs/en/6.26.3/babelrc#env-option) in your babel configuration file – with different configurations of this plugin.

**Comment by goatandsheep** [comment]
@SirKadogan @Sterlingryan this feature has now been implemented in the latest release of related repo https://github.com/goatandsheep/react-native-dotenv , but @tusbar is correct that you can also specify different environments in your babel config
