### ISSUE TITLE
Possible for logic in env file?

### ISSUE THREAD

**Issue by CyberMew** [tusbar/babel-plugin-dotenv-import#194]
I want to set (or unset) variables if running Android or/and iOS. Is that possible for this plugin?

**Comment by goatandsheep** [comment]
.env

```
EXAMPLE_ENV_IOS=I am iPhone only
EXAMPLE_ENV_ANDROID=I am Android only
```

Then choose the env var you want using the platform https://reactnative.dev/docs/platform-specific-code
