### ISSUE TITLE
React Native cannot load module fs (file system)

### ISSUE THREAD

**Issue by danactive** [tusbar/babel-plugin-dotenv-import#8]
`const {readFileSync} = require('fs')` should be replaced with https://stackoverflow.com/questions/39046429/react-native-unable-to-resolve-module-fs#39046690

![screen shot 2018-04-03 at 14 17 08](https://user-images.githubusercontent.com/1093286/38276396-bb602eaa-3749-11e8-83c0-48161efc1996.png)

**Comment by tusbar** [comment]
Hello @danactive 

I’m not sure I understand this error, this is a babel plugin so it should only be a dependency that runs on your machine and not in your app?

**Comment by danactive** [comment]
AFAIK React Native runs a web server in the app without access to Node.js features like the file system.

By reading your reply, maybe this module is intended for build time and not execution time like I'm trying

**Comment by tusbar** [comment]
Yeah of course you wouldn’t have access to the file system in an iOS app. 🍎 

This module is indeed intended for build time, like all babel modules. :)

**Comment by danactive** [comment]
Closing ticket, noting this module does not support React Native runtime
